config/routes.rb
Rails.application.routes.draw do
	resources :articles do
		resources :comments
	end
	root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	#Аутентификация на создание, изменение
	http_basic_authenticate_with name: "d", password: "s", except: [:index, :show]
	
	#Главная
	def index
		@articles = Article.all
	end
	
	#Показать
	def show
		@article = Article.find(params[:id])
	end
	
	#Новая
	def new
		@article = Article.new
	end
	
	#Изменить
	def edit		
		@article = Article.find(params[:id])
	end
	
	#Создать
	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end
	
	#Изменить
	def update		
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end
	
	#Удалить
	def destroy		
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end
	
	#Объяление
	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	#Аутентификация на удаление
	http_basic_authenticate_with name: "d", password: "s", only: :destroy
	
	#Создать
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end
	
	#Удалить
	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end
	
	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form_edit.erb
<%= form_for @article do |f| %>

	<% if @article.errors.any? %>
		<div id = "error_explanation">
			<h2>
				Ошибки:
			</h2>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<%end%>
	
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</P>
	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</P>
	<p>
		<%= f.submit %>
	</P>
<% end %>

<%= link_to 'Назад', articles_path %>
<%= link_to 'На главную', root_path %>

app/views/articles/_form_show.erb
<p>
	<strong>Заголовок:</strong>
	<%= @article.title %>
</P>
<p>
	<strong>Текст:</strong>
	<%= @article.text %>
</P>

app/views/articles/edit.html.erb
<h1>Редактор</h1>
<%= render 'form_edit' %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'Новая статья', new_article_path %>
<%= link_to 'На главную', root_path %>

<table>
	<tr>	
		<th>Title</th>
		<th>Text</th>
	</tr>
	
	<% @articles.each do |article| %>
		<tr>
			<td><%= article.title %></td>
			<td><%= article.text %></td>
			<td><%= link_to 'Показать', article_path(article) %></td>
			<td><%= link_to 'Редактировать', edit_article_path(article) %></td>
			<td><%= link_to 'Удалить', article_path(article.id), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
		</tr>
	<%end%>
</table>

app/views/articles/new.html.erb
<h1>Новая статья</h1>
<%= render 'form_edit' %>

app/views/articles/show.html.erb
<%= link_to 'Редактировать', edit_article_path %>

<%= render 'form_show' %>

<h2>Комментарий:</h2>
<%= render @article.comments %>

<h2>Добавить комментарий:</h2>
<%= render 'comments/form_comment' %>

<%= link_to 'Назад', articles_path %>
<%= link_to 'На главную', root_path %>

app/views/comments/_comment.html.erb
<p>
	<strong>Пользователь:</strong>
	<%= comment.commenter %>
</P>
<p>
	<strong>Комментарий:</strong>
	<%= comment.body %>
</P>

<p>
	<%= link_to 'Удалить комментарий', [comment.article, comment], method: :delete, data: { confirm: 'Вы уверены?' } %>
</P>

app/views/comments/_form_comment.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %><br>
		<%= f.text_field :commenter %>
	</P>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</P>
	<p>
		<%= f.submit %>
	</P>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>hello welcome!</h1>

<%= link_to 'Мой блог', controller: 'articles' %>